[package]
name = "alkanes-generator"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.94"
serde_json = "1.0.140"
image = { version = "0.24", default-features = false, features = ["png"] }
include_dir = "0.7"
hex = "0.4"
